name = "fantasy-auto-gm-approvals"
main = "src/index.js"
compatibility_date = "2026-09-01"

[triggers]
crons = ["0 * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "fantasy-auto-gm-approvals"
database_id = "cd137212-546b-46fb-aa0f-bb8a2d84baa5"
migrations_dir = "migrations"

